### ISSUE TITLE
Problem with perl's rename

### ISSUE THREAD

**Issue by EugeneBragin** [tseemann/VelvetOptimiser#22]
In certain circumstances perl's rename would fail quietly. 
https://github.com/tseemann/VelvetOptimiser/blob/master/VelvetOptimiser.pl#L404
This happens for example when using velvetoptimiser in a docker container when -d is set to another volume.
Tracing the error gives following:
bash-4.2# perl -e "rename('/auto_data_83','/data/assembly') or die \$!;"
Invalid cross-device link at -e line 1.
Would be great have the exception handled with or die ...$! and/or perhaps consider using `mv`?

P.S.
https://www.unix.com/shell-programming-and-scripting/27747-perl-rename-failed.html

**Comment by Slugger70** [comment]
Thanks Eugene. I'll look into it.

**Comment by Slugger70** [comment]
Fixed in PR #23
