### ISSUE TITLE
Added option for reusing sequences

### ISSUE THREAD

**Issue by sestaton** [tseemann/VelvetOptimiser#3]
We have run into issues with disk space when trying to assemble large data sets and use a range of hash values. The problem is that the sequences are written to disk for every single hash step, and this is both time consuming and costly (in terms of shared resources). I have modified VelvetOptimiser to reuse the sequences, so they are processed only once. There is no change in the usage of the program and it works exactly as before with single or multiple threads. You can try it out from this branch:

https://github.com/sestaton/VelvetOptimiser/tree/topic/reuse_sequences

Please let me know if anyone finds issues.

**Comment by tseemann** [comment]
We are unable to make any major changes to VOpt over the last few years due to lack of time, and lack of use of the software now that more suitable software is available.
